version: '2'

services:

  mailcatcher:
    image: spartakusmd/mailcatcher:$VERSION
    build:
      context: build
      args:
        MAILCATCHER_VERSION: $VERSION
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
